# Generated by Django 4.0.6 on 2022-07-31 14:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='from_date',
            new_name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='num_people',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='to_date',
        ),
        migrations.AddField(
            model_name='bookings',
            name='arrival_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booking.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 19, 31, 22, 73494)),
        ),
    ]
