# Generated by Django 4.0.6 on 2022-07-31 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_from_date_bookings_arrival_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booked_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 20, 3, 23, 216242)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 20, 3, 23, 200524)),
        ),
    ]
