# Generated by Django 4.0.6 on 2022-07-31 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookings_booked_on_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='adults',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='bookings',
            name='car_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookings',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pickup_from_airport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookings',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booked_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 20, 51, 58, 5722)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 20, 51, 58, 5722)),
        ),
        migrations.DeleteModel(
            name='BookingDetails',
        ),
    ]
